### ISSUE TITLE
Tehran zone is +3:30 but in this package is +4:30

### ISSUE THREAD

**Issue by mostafabarmshory** [stub42/pytz#104]
Dear developers,

I was faced with an issue. I use Asia/Tehran or Iran as the time zone. I expect +3:30 but the result is +4:30.

How can I fix this?

**Comment by mostafabarmshory** [comment]
I can fix this issue by my self, if you help me to know how. Would you please?

**Comment by marinellirubens** [comment]
Hello @mostafabarmshory  I was having a similar issue, also created a issue explaining the problem https://github.com/stub42/pytz/issues/107, on the issue I informed that there is a workaround that can be used, please take a look maybe it can help you as well, hope this issue is fixed in the future.

**Comment by Sanazzzmi** [comment]
I have the same problem. No one has a solution for it?

**Comment by mostafabarmshory** [comment]
Here is a PR waiting for approve.

https://github.com/stub42/pytz/pull/110

**Comment by stub42** [comment]
pytz is working as expected. Make sure you are constructing localized timestamps correctly, per the [pytz README](https://github.com/stub42/pytz/blob/master/src/README.rst#localized-times-and-date-arithmetic)

```
Python 3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytz
>>> from datetime import datetime
>>> tz = pytz.timezone('Asia/Tehran')
>>> tz.localize(datetime.now())
datetime.datetime(2023, 8, 13, 13, 8, 24, 779310, tzinfo=<DstTzInfo 'Asia/Tehran' +0330+3:30:00 STD>)
>>>
```

**Comment by stub42** [comment]
pytz 2021.1 was released in 2021. You want the latest version with the latest database (2023.3)
