### ISSUE TITLE
Spelling error for Kyiv

### ISSUE THREAD

**Issue by prayagnshah** [stub42/pytz#106]
Hello Team, 

I see a small spelling error for **Europe/Kiev** instead of that it should be **Europe/Kyiv**. 

Proof: https://en.wikipedia.org/wiki/Kyiv

Not sure if its a big mistake.

**Comment by hugovk** [comment]
And the timezone was renamed to Europe/Kyiv in IANA's Time Zone Database release 2022b, and Europe/Kiev kept as an alternative:

>   Changes to zone name
>
>    Rename Europe/Kiev to Europe/Kyiv, as "Kyiv" is more common in
    English now.  Spelling of other names in Ukraine has not yet
    demonstrably changed in common English practice so for now these
    names retain old spellings, as in other countries (e.g.,
    Europe/Prague not "Praha", and Europe/Sofia not "Sofiya").

https://data.iana.org/time-zones/tzdb/NEWS
