### ISSUE TITLE
Bad link in unofficial (?) documentation on sourceforge

### ISSUE THREAD

**Issue by sterliakov** [stub42/pytz#115]
Here's the page I refer to: https://pytz.sourceforge.net/

It is the first Google result by "pytz documentation" query for me. It has maintainer name at the page top.

Scroll to the very bottom and find a "Further reading" section. There is a link that points to a site that certainly has nothing to do with timezones. Scroll that page down to see that it's some SEO shit for a pornsite pretending to be some legit, though very badly designed, website. I do not copy URL here intentionally to prevent spreading this. 

Do `pytz` maintainers have access to that sourceforge page source? The README section contains another link, and blame view on GitHub suggests that it was never changed.

If you have such access, please update the link. If not - please consider adding a warning about this being unofficial documentation to README here, and maybe try to contact with site owner to stop using your name on that document.

**Comment by stub42** [comment]
Nuked the Sourceforge project. It wasn't helpful.
