### ISSUE TITLE
Pyoungyang time zone issue.

### ISSUE THREAD

**Issue by knight76** [stub42/pytz#15]
Hi!

I found a time zone issue which changed Pyongyang(North Korea) time zoned recently.
According to 'https://en.wikipedia.org/wiki/Time_in_North_Korea', I found 'On 29 April 2018, North Korean leader Kim Jong-un announced his country would be returning to UTC+9 to realign its clocks with South Korea. '. It based on the Guadian Newspaper('https://www.theguardian.com/world/2018/may/05/time-for-change-north-korea-moves-clocks-forward-to-match-south')

Below code is not match the Wiki. 
```
import pytz
import datetime

def main():
	
	seoul = pytz.timezone('Asia/Seoul')
	print(seoul.localize(datetime.datetime.now()))
	
	pyongyang = pytz.timezone('Asia/Pyongyang')
	print(pyongyang.localize(datetime.datetime.now()))
	
if __name__ == '__main__':
	main()
```

The result is below.
```
2018-06-19 18:23:36.818206+09:00
2018-06-19 18:23:36.818469+08:30
```

Second result should be equal to '2018-06-19 18:23:36.818469+09:00'

Could you change code and and document(https://github.com/stub42/pytz/blob/master/tz/asia#L1997)? 

And When I test the previous example, I found another interesting sample code.

```
>>> import pytz

>>> from datetime import datetime

>>> fmt = '%Y-%m-%d %H:%M:%S %Z%z'

>>> seoul = pytz.timezone('Asia/Seoul')

>>> seoul

<DstTzInfo 'Asia/Seoul' KST+8:30:00 STD>
```

```
>>> pyongyang = pytz.timezone('Asia/Pyongyang')
>>> pyounyang

<DstTzInfo 'Asia/Pyongyang' KST+8:30:00 STD>
```

Finally, I found another interesting document. You described world timezone. Previsous menthioned, I think it should be changed. 

https://github.com/stub42/pytz/blob/master/tz/asia#L47
https://github.com/stub42/pytz/blob/master/tz/asia#L50
-> I think it should be removed at '8:30 KST  KDT	Korea when at +0830', maintained at ''9:00 KST  KDT	Korea when at +09'.

Thanks in advance.

**Comment by stub42** [comment]
New version is (finally) out with the updated database.

**Comment by nutrino** [comment]
pytz 2021.3 version still has an error.
```python
import pandas as pd
import pytz
import datetime

pd.Timestamp('2023-05-24 17:00:00+0900', tz='Asia/Seoul') == datetime.datetime(2023, 5, 24, 16, 28, tzinfo=pytz.timezone('Asia/Seoul')) # True

pd.Timestamp('2023-05-24 17:00:00+0900', tz='Asia/Seoul') == pytz.timezone('Asia/Seoul').localize(datetime.datetime(2023, 5, 24, 17, 0)) # True
```
