### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by bdfy** [stub42/pytz#2]
#!/usr/bin/python3.5

from dateutil.parser import parse
import pytz

lists = [
"20170824010000 +0300",
"20170824015500 +0300",
"20170824034500 +0300",
"20170824052500 +0300",
"20170824210000 +0300",
"20170824232500 +0300"
]

for row in lists:
    print (parse(row).replace(tzinfo=pytz.timezone('Europe/Moscow')))

result:
2017-08-24 01:00:00+02:30
2017-08-24 01:55:00+02:30
2017-08-24 03:45:00+02:30
2017-08-24 05:25:00+02:30
2017-08-24 21:00:00+02:30
2017-08-24 23:25:00+02:30

**Comment by stub42** [comment]
This is expected behaviour, per https://pypi.python.org/pypi/pytz (particularly
