### ISSUE TITLE
Getting error when running `make test`

### ISSUE THREAD

**Issue by chapayevdauren** [stub42/pytz#25]
make -C ./tz TOPDIR=`pwd`/build USRDIR= USRSHAREDIR=etc install
make[1]: Entering directory '/home/dauren/work/backend/pytz/tz'
awk -v DATAFORM=`expr main.zi : '\(.*\).zi'` -f ziguard.awk \
	  africa antarctica asia australasia europe northamerica southamerica etcetera systemv factory backward  >main.zi.out
malloc(): memory corruption
Aborted (core dumped)
Makefile:586: recipe for target 'main.zi' failed
make[1]: *** [main.zi] Error 134
make[1]: Leaving directory '/home/dauren/work/backend/pytz/tz'
Makefile:134: recipe for target '.stamp-zoneinfo' failed
make: *** [.stamp-zoneinfo] Error 2

**Comment by stub42** [comment]
This failure is coming from the IANA timezone code that gets pulled in, and if it was a bug has hopefully been addressed there. I have never seen it in my build or test environments.
