### ISSUE TITLE
Invalid duration between datetime (looks like invalid NewYork tz info)

### ISSUE THREAD

**Issue by Artiomtb** [stub42/pytz#27]
Looks like smth wrong with datetime difference with pytz timezones. I have such code on Python 3.6:

```
import datetime
import pytz

dep_datetime = pytz.timezone('America/New_York').localize(
    datetime.datetime.strptime(
        '2019-11-03 01:05:00',
        '%Y-%m-%d %H:%M:%S'
    )
)
arrival_datetime = pytz.timezone('Europe/Amsterdam').localize(
    datetime.datetime.strptime(
        '2019-11-03 13:00:00',
        '%Y-%m-%d %H:%M:%S'
    )
)

diff = arrival_datetime - dep_datetime
print(diff)
diff_minutes = int((diff).total_seconds() / 60)
print(diff_minutes)
exit(1)
```

Returns:
5:55:00
355

I have similar code on PHP and go, and their result is 415 minutes (6 hours 55 minutes). Such result also shows online calculator: https://www.timeanddate.com/date/timezoneduration.html?d1=3&m1=11&y1=2019&d2=3&m2=11&y2=2019&h1=01&i1=05&s1=00&h2=13&i2=00&s2=&

I also checked this case in docker (latest python, latest php and go) and results didn't change - 355 minutes in python, 415 in other languages.

Could you help me with this case?

This is copy of https://bugs.launchpad.net/pytz/+bug/1829385

**Comment by stub42** [comment]
Per Launchpad
