### ISSUE TITLE
bdist_wheel fails due to AssertionError 

### ISSUE THREAD

**Issue by tommyli3318** [stub42/pytz#30]
```
$ python src/setup.py bdist_wheel
Traceback (most recent call last):
  File "src/setup.py", line 25, in <module>
    assert len(resources) > 10, 'zoneinfo files not found!'
AssertionError: zoneinfo files not found!
```

This only started happening ever since the most recent commits.
I tried running `python setup.py install` and I get the same AssertionError

**Comment by stub42** [comment]
The zoneinfo files and a chunk of the python code doesn't exist until the build step is run. 'make build' first, then you can find working code and zoneinfo files in build/dist.
