### ISSUE TITLE
"CET" should be included in `common_timezones`

### ISSUE THREAD

**Issue by skebanga** [stub42/pytz#32]
As per the documentation:

> `common_timezones` is a list of useful, current timezones. It doesn’t contain deprecated zones or historical zones, except for a few I’ve deemed in common usage, such as US/Eastern (open a bug report if you think other timezones are deserving of being included here)

Central European Time is commonly used by all countries in central Europe.

As such, CET should be in `common_timezones`

**Comment by stub42** [comment]
CET is a timezone abbreviation, and not an IANA timezone identifier. It only exists in the IANA database for backwards compatibility. If a proper IANA timezone identifier is needed for Central European Time (eg. Europe/Central), that needs to be raised on the IANA timezone database mailing list.
