### ISSUE TITLE
Should "FixedOffset" be part of the public API

### ISSUE THREAD

**Issue by janpipek** [stub42/pytz#34]
Hi,

first, thanks for managing this nice library!

I have problems with `mypy` when using the `FixedOffset` function:

```
some_file.py:4: error: Module 'pytz' has no attribute 'FixedOffset'
```

I found out that this is probably related to "FixedOffset" not being exported in `__all__` and thus also not present in `typeshed` database. So my question is - Is the function (quite a useful one!) hidden by purpose or can it be public as well?

Thanks a lot,
Jan

Related: https://answers.launchpad.net/pytz/+question/671489

**Comment by stub42** [comment]
It is supposed to be public

**Comment by janpipek** [comment]
Ok, thanks. I created a minimalist PR implementing this.
