### ISSUE TITLE
Comparing datetime.time objects incorrect for TZ aware and unaware

### ISSUE THREAD

**Issue by mikessut** [stub42/pytz#38]
I filled this as a bug on python because I thought it was the datetime comparison.  Apparently, it is actually something with pytz (which I don't fully understand).

https://bugs.python.org/issue38812

```
import pytz
import datetime

tzaware_time1 = datetime.time(7,30,tzinfo=pytz.timezone("America/Denver"))
tzaware_time2 = datetime.time(7,30,tzinfo=pytz.utc)

tzunaware_time = datetime.time(7, 30)

# This fails with exception: TypeError: can't compare offset-naive and offset-aware times
# even though both ARE tz aware.
tzaware_time1 < tzaware_time2

# This does NOT raise an exception and should since one is aware and one isn't.
tzunaware_time < tzaware_time1
```

**Comment by stub42** [comment]
datetime.time isn't going to work with pytz. There is no date component, so it is unknown which of the several timezone rules America/Denver has used over the years applies.
