### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by mross22** [stub42/pytz#4]
Is there a changelog file anywhere that indicates what the changes are in each release? I'm attempting to upgrade from an earlier version but it would be nice to know what has changed.

**Comment by stub42** [comment]
Git commitlog is the best we have. The project has been in maintenance mode, with infrequent code updates, and the existing CHANGES.txt is out of date.

**Comment by GliderGeek** [comment]
fwas looking for this as well and found https://github.com/stub42/pytz/blob/master/tz/NEWS
