### ISSUE TITLE
Setting the  timezone in tz_localize('ETC/GMT+2) causes a shift in opposite direction

### ISSUE THREAD

**Issue by EbrahimKaram** [stub42/pytz#41]
https://github.com/pandas-dev/pandas/issues/12823
Please check the error in the link above
df2_5['Time'].dt.tz_localize('ETC/GMT+2')
cause the localization to be 
2489   2020-03-30 08:00:00-02:00
2490   2020-03-30 09:00:00-02:00
2491   2020-03-30 10:00:00-02:00
2492   2020-03-30 11:00:00-02:00
2493   2020-03-30 12:00:00-02:00

instead of +2 

Unless I'm using it wrong

**Comment by stub42** [comment]
This is how POSIX defined it decades ago, and it has been confusing people ever since.
