### ISSUE TITLE
Base class for all errors in the library

### ISSUE THREAD

**Issue by besfahbod** [stub42/pytz#43]
Would be great to have a single "base" class for all errors that could be raised by the library.

Looking at https://github.com/stub42/pytz/blob/master/src/pytz/exceptions.py, there are two base classes at the moment: `UnknownTimeZoneError` and `InvalidTimeError`.

Without a guaranteed single base class, a package upgrade may add new error types, without call-sites being updated about the change.

**Comment by stub42** [comment]
Agreed. I'm surprised they don't already share a base class.

**Comment by besfahbod** [comment]
Thanks for taking care of this, @stub42! :)
