### ISSUE TITLE
`pytz.all_timezones` returns entities which aren't timezones

### ISSUE THREAD

**Issue by gothill** [stub42/pytz#46]
`pytz.all_timezones` ought to return a list of timezones, but it contains strings like `CET` and `GMT` which aren't timezones, but offsets. They are officially deprecated in the tz database https://en.wikipedia.org/wiki/List_of_tz_database_time_zones 

```
>>> 'CET' in pytz.all_timezones
True
```

i.e. CET is an _offset_ of +1 relative to UTC
However, the `Europe/Berlin` _timezone_ switches between CET and CEST (UTC+2) depending on the time of the year.

A timezone is by established convention not the same thing as an offset:
https://stackoverflow.com/tags/timezone/info

I stumbled on this while trying to use `pytz.all_timezones` to validate IANA timezone strings, e.g. `Europe/Berlin`.

**Comment by stub42** [comment]
These are legacy timezones in the IANA Timezone Database, and while they deprecated for good reason they remain in the IANA Timezone Database for backwards compatibility. all_timezones in pytz lists all the IANA Timezone Database's timezones, including the deprecated ones. You will need to filter out the entries that don't meet your requirements in your application or a wrapper.
