### ISSUE TITLE
Unknown Time Zone for `BST`?

### ISSUE THREAD

**Issue by scottwallacesh** [stub42/pytz#71]
After daylight savings started earlier this week we are now seeing:
```
pytz.exceptions.UnknownTimeZoneError: 'BST'
```

**Comment by scottwallacesh** [comment]
`BST` is coming from `datetime.datetime.today().astimezone().tzinfo`

**Comment by stub42** [comment]
The argument to pytz.timezone must be an IANA timezone identifier. BST is a timezone abbreviationdatetime.astimezone().tzname() is not guaranteed to return a timezone identifier, and is platform dependent. My guess is the host system was configured to use 'BST' as the timezone identifier, which may work for backwards compatibility, but that newer versions of the IANA timezone database no longer accept it. 'Europe/London' is normally the correct string to configure a Unix or Linux host with, which I think would cause tzname() to return a value that happens to be a valid IANA timezone identifier.

**Comment by scottwallacesh** [comment]
The system was configured by the Ubuntu installer and I'm not the only person to have this issue.

**Comment by scottwallacesh** [comment]
Here's a quick example of setting the timezone using the IANA timezone identifiers but `tzname()` returning abbreviations.

Code:
```python
import os
import time
import datetime

def test_tz(zone):
    os.environ['TZ'] = zone
    time.tzset()
    print(f'Timezone: {zone}')
    print(f'TZ name: {datetime.datetime.today().astimezone().tzname()}')

test_tz('America/Chicago')
test_tz('Australia/Brisbane')
test_tz('Europe/London')
```

Output:
```plain
Timezone: America/Chicago
TZ name: CDT
Timezone: Australia/Brisbane
TZ name: AEST
Timezone: Europe/London
TZ name: BST
```
