### ISSUE TITLE
Change of timezone name Europe/Kiev to Europe/Kyiv and Europe/Zaporozhye to Europe/Zaporizhzhia

### ISSUE THREAD

**Issue by vizvasrj** [stub42/pytz#83]
"Europe/Kiev", "Europe/Zaporozhye" are to be changed into
"Europe/Kyiv", "Europe/Zaporizhzhia" respectively

https://phabricator.wikimedia.org/T149523

**Comment by hyzyla** [comment]
Try to update package, corresponding change was made in IANA database in September 2022  [1]

1. https://data.iana.org/time-zones/tzdb/NEWS

<img width="555" alt="image" src="https://user-images.githubusercontent.com/7952949/229315327-72fba624-b48d-4daf-aaed-bc60d13a3461.png">


<img width="694" alt="image" src="https://user-images.githubusercontent.com/7952949/229315374-9746f1de-d5e5-4d5d-954c-ff6dbb035607.png">
