### ISSUE TITLE
l18n package recommendation

### ISSUE THREAD

**Issue by wombatonfire** [stub42/pytz#92]
This is a documentation improvement suggestion.

The [Internationalization - i18n/l10n](https://github.com/stub42/pytz/blob/master/src/README.rst#internationalization---i18nl10n) section of the README recommends using [l18n](https://pypi.org/project/l18n/) package for time zone translation/formatting. As of today, it seems that this package is not being actively maintained. It's lagging behind the recent pytz versions, the latest release was more than a year ago.

While it seems to work for most of the current time zones, there are issues as well: the recently changed names for Europe/Kyiv and Pacific/Kanton zones are not recognized.

It may be a good idea to change the recommended package for i18n/l10n to something else. Babel can be a good option, specifically its [time zone functionality](https://babel.pocoo.org/en/latest/api/dates.html#timezone-functionality) in the `babel.dates` module. Babel seems to be actively maintained, it works for all current time zones, and it provides more features than the currently recommended package. Also, Babel's datetime/tz functionality in turn depends on pytz, so I would expect better compatibility with the new pytz versions moving forward.

**Comment by stub42** [comment]
Ta. Updated.
